spring:
    security:
        user:
            name: mocadev
            password: 1234

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: root
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
